insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Della Skunes', 'Cybersecurity');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Lucas Trunchion', 'eHealth');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Waylen Skeffington', 'Digital Forensics');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Clareta Moyce', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Constance Yearne', 'Systems Security');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Bettine Celli', 'Data Analytics');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Almeta Dobbs', 'Digital Investigations');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Annaliese Mulford', 'Digital Systems Technology');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Joyan Godsell', 'Embedded Systems');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Peria Peealess', 'Information Technology Entrepreneurship');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Laetitia Yoell', 'Information Systems Management');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Channa Christensen', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Claiborn Bartomeu', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Giffie Colleer', 'Computational Modelling');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Dix Tinn', 'Artificial Intelligence');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Kania Chaunce', 'eHealth');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Norma Tremblet', 'Embedded Systems and IoT');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Fulton Bavister', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Judd O''Grady', 'Mobile and Wireless communications');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Greta Fike', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Pepita O'' Loughran', 'Multimedia and e-Learning');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Letisha Stollenberg', 'Security and Privacy');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Normie Greschik', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Hirsch Greenin', 'Cybersecurity');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Sacha Durno', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Nelly Collidge', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Addison Giovannoni', 'Systems Security');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Rafaelia Vassano', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Huey Philbin', 'Data Analytics');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Jeniece Gubbin', 'Embedded Systems');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Patti Macieja', 'Information Systems Management');
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Penny Mogey', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Ilyssa Basden', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Benjy Twigley', null);
insert into TRAINERS (TrainerName, TrainerSpecialisation) values ('Prescott Kopf', null);
